### ISSUE TITLE
Collectd error

### ISSUE THREAD

**Issue by darrepac** [mstojek/nlbw2collectd#1]
Hi

Whatever I did I have always this error when I select statistics > graphs : 
![IMG_3734](https://github.com/mstojek/nlbw2collectd/assets/7128994/12dda40b-3afb-4a88-ae61-6187a4ba7336)

any hint?
Thx

**Comment by mstojek** [comment]
Could you please share with me your statistics config:
cat /etc/config/luci_statistics

niedz., 10 gru 2023, 22:10 użytkownik darrepac ***@***.***>
napisał:

**Comment by darrepac** [comment]
config statistics 'collectd'
        option BaseDir '/var/run/collectd'
        option PIDFile '/var/run/collectd.pid'
        option PluginDir '/usr/lib/collectd'
        option TypesDB '/usr/share/collectd/types.db'
        option Interval '30'
        option ReadThreads '2'
        option Include '/etc/collectd/conf.d/*.conf'
        option FQDNLookup '1'

config statistics 'rrdtool'
        option default_timespan '1hour'
        option image_width '600'
        option image_height '150'
        option image_path '/tmp/rrdimg'

config statistics 'collectd_rrdtool'
        option enable '1'
        option DataDir '/tmp/rrd'
        option RRARows '288'
        option RRASingle '1'
        list RRATimespans '1hour'
        list RRATimespans '1day'
        list RRATimespans '1week'
        list RRATimespans '1month'
        list RRATimespans '1year'

config statistics 'collectd_csv'
        option enable '0'
        option StoreRates '0'
        option DataDir '/tmp'

config statistics 'collectd_email'
        option enable '0'
        option SocketFile '/var/run/collectd/email.sock'
        option SocketGroup 'nogroup'

config statistics 'collectd_logfile'
        option enable '0'
        option LogLevel 'notice'
        option File '/var/log/collectd.log'
        option Timestamp '1'

config statistics 'collectd_network'

config statistics 'collectd_syslog'
        option enable '0'
        option LogLevel 'warning'
        option NotifyLevel 'WARNING'

config statistics 'collectd_unixsock'
        option enable '0'
        option SocketFile '/var/run/collectd/query.sock'
        option SocketGroup 'nogroup'

config statistics 'collectd_apcups'
        option enable '0'
        option Host 'localhost'
        option Port '3551'

config statistics 'collectd_chrony'
        option enable '0'
        option Host '127.0.0.1'
        option Port '323'
        option Timeout '2'

config statistics 'collectd_conntrack'
        option enable '0'

config statistics 'collectd_contextswitch'
        option enable '0'

config statistics 'collectd_cpu'
        option enable '1'
        option ReportByCpu '1'
        option ReportByState '1'
        option ShowIdle '0'
        option ValuesPercentage '1'

config statistics 'collectd_cpufreq'
        option enable '0'

config statistics 'collectd_curl'
        option enable '0'

config statistics 'collectd_df'
        option enable '0'
        option Devices '/dev/mtdblock/4'
        option MountPoints '/overlay'
        option FSTypes 'tmpfs'
        option IgnoreSelected '0'
        option ValuesPercentage '0'

config statistics 'collectd_dhcpleases'
        option enable '0'
        option Path '/tmp/dhcp.leases'

config statistics 'collectd_disk'
        option enable '0'
        option Disks 'hda1 hdb'
        option IgnoreSelected '0'

config statistics 'collectd_dns'
        option enable '0'
        option Interfaces 'br-lan'
        option IgnoreSources '127.0.0.1'

config statistics 'collectd_entropy'
        option enable '0'

config statistics 'collectd_exec'
        option enable '0'

config statistics 'collectd_interface'
        option enable '1'
        option Interfaces 'br-lan'
        option IgnoreSelected '0'

config statistics 'collectd_ipstatistics'
        option enable '0'

config statistics 'collectd_iptables'
        option enable '0'

config collectd_iptables_match
        option table 'nat'
        option chain 'luci_fw_postrouting'
        option target 'MASQUERADE'
        option source '192.168.1.0/24'
        option outputif 'br-ff'
        option name 'LAN-Clients traffic'

config collectd_iptables_match
        option chain 'luci_fw_postrouting'
        option table 'nat'
        option target 'MASQUERADE'
        option source '10.61.230.0/24'
        option outputif 'br-ff'
        option name 'WLAN-Clients traffic'

config statistics 'collectd_irq'
        option enable '0'
        option Irqs '2 3 4 7'

config statistics 'collectd_iwinfo'
        option enable '1'

config statistics 'collectd_load'
        option enable '1'

config statistics 'collectd_memory'
        option enable '1'
        option ValuesAbsolute '1'
        option ValuesPercentage '0'

config statistics 'collectd_netlink'
        option enable '0'
        option IgnoreSelected '0'
        option VerboseInterfaces 'br-lan'
        option QDiscs 'br-lan'

config statistics 'collectd_nut'
        option enable '0'
        list UPS 'myupsname'

config statistics 'collectd_olsrd'
        option enable '0'
        option Port '2006'
        option Host '127.0.0.1'

config statistics 'collectd_openvpn'
        option enable '0'

config statistics 'collectd_ping'
        option enable '0'
        option TTL '127'
        option Interval '30'
        option Hosts '127.0.0.1'

config statistics 'collectd_processes'
        option enable '0'
        option Processes 'uhttpd dnsmasq dropbear'

config statistics 'collectd_sensors'
        option enable '0'

config statistics 'collectd_snmp6'
        option enable '0'
        option Interfaces 'br-lan'
        option IgnoreSelected '0'

config statistics 'collectd_splash_leases'
        option enable '0'

config statistics 'collectd_tcpconns'
        option enable '0'
        option ListeningPorts '0'
        option LocalPorts '22 80'

config statistics 'collectd_thermal'
        option enable '1'

config statistics 'collectd_uptime'
        option enable '0'

**Comment by mstojek** [comment]
I see that you enabled CPU statistics, are you able to display them or you see no statistics at all?
For the further debug I would like to see colectd logs:
`# logread | grep collectd`
 
Then let us see if we have any iptables statistics created by my plugin:
`# ls -l /tmp/rrd/*/iptables-mangle-*/*`

**Comment by darrepac** [comment]
root@OpenWrt:~# logread | grep collectd
root@OpenWrt:~# ls -l /tmp/rrd/*/iptables-mangle-*/*
ls: /tmp/rrd/*/iptables-mangle-*/*: No such file or directory

**Comment by mstojek** [comment]
Maybe let us check first if you have luci-app-statistics and collectd installed:

`# opkg list-installed | grep collectd`

`# opkg list-installed | grep luci-app-statistics`


We should see something like this:

```
# opkg list-installed | grep collectd
[...]
collectd - 5.12.0-10
[...]
collectd-mod-lua - 5.12.0-10
[...]

# opkg list-installed | grep luci-app-statistics
luci-app-statistics - git-22.115.68435-0473e99

```

**Comment by darrepac** [comment]
```
root@OpenWrt:~# opkg list-installed | grep collectd
collectd - 5.12.0-34
collectd-mod-cpu - 5.12.0-34
collectd-mod-interface - 5.12.0-34
collectd-mod-iwinfo - 5.12.0-34
collectd-mod-load - 5.12.0-34
collectd-mod-lua - 5.12.0-34
collectd-mod-memory - 5.12.0-34
collectd-mod-network - 5.12.0-34
collectd-mod-rrdtool - 5.12.0-34
root@OpenWrt:~# opkg list-installed | grep luci-app-statistics
luci-app-statistics - git-23.338.82069-2c59ace


```
not so bad ;)

**Comment by mstojek** [comment]
Strange, I suspected that it is not installed since `# logread | grep collectd` returned nothing.
 Let us check if collectd is actually running:
`# ps | grep collectd`

We should get:
```
# ps | grep collectd
13424 root      9148 SN   /usr/sbin/collectd -C /tmp/collectd.conf -f
19837 root      1252 S    grep collectd

```
If it is not running try:

```
# /etc/init.d/luci_statistics enable
# /etc/init.d/luci_statistics start

```
and then run again
`# ps | grep collectd`

**Comment by darrepac** [comment]
Indeed, nothing running... but enabling/starting luci_statiscics did not
solve it...
***@***.***:~# /etc/init.d/luci_statistics status
active with no instances

**Comment by mstojek** [comment]
What is `# logread | grep collectd` saying now? Still empty? We need some logs that will tell us why collectd is not running.

**Comment by darrepac** [comment]
> What is `# logread | grep collectd` saying now? Still empty? We need some logs that will tell us why collectd is not running.

unfortunately still empty

**Comment by darrepac** [comment]
```
root@OpenWrt:~# collectd
plugin_load: plugin "lua" successfully loaded.
Lua plugin: File "/usr/share/collectd-mod-lua/nlbw2collectd.lua" loaded successfully
plugin_load: plugin "iwinfo" successfully loaded.
plugin_load: plugin "memory" successfully loaded.
plugin_load: plugin "cpu" successfully loaded.
plugin_load: plugin "load" successfully loaded.
plugin_load: plugin "rrdtool" successfully loaded.
rrdtool plugin: RRASingle = true: creating only AVERAGE RRAs
plugin_load: Could not find plugin "thermal" in /usr/lib/collectd
plugin_load: plugin "interface" successfully loaded.
Error: Parsing the config file failed!
```
Is it of any help?

**Comment by mstojek** [comment]
Seems that you have errors in your collectd config file. 
Maybe executing `# /etc/init.d/luci_statistics restart` will help.
If not can you try to edit statistics configuration in Luci? Click on the `"Setup collectd" ` icon seen in picture in your first message. Then configure e.g. collecting CPU statistics, Save and Apply config changes and check the results.

**Comment by darrepac** [comment]
That's why it is always asking to setup collectd...but whatever I do in settings, it doesn't work.
I am running openwrt 22.03, may-be I should update it...

**Comment by mstojek** [comment]
Googled a little, and found this command to find corrupted config files:
`for x in /etc/config/*; do uci show "${x##*/}" >/dev/null || echo "$x is broken"; done
`
Found in: https://forum.openwrt.org/t/uci-parse-error-executing-luci-statistics/142209
One more this is to remove my script config file to double check that it does not make problems here: 
`# rm /etc/collectd/conf.d/lua.conf`

You can also copy here your collectd config file, maybe we will find and fix error here:
`# cat /etc/collectd.conf`

If that will not help probably you need to go with upgrade. Something is messed in your Openwrt installation. You should be able to see at least CPU stats with few clicks in Luci.

**Comment by darrepac** [comment]
I did an upgrade but the problem remains...

```
root@OpenWrt:~# cat /etc/collectd.conf
BaseDir "/var/run/collectd"
Include "/etc/collectd/conf.d/*.conf"
PIDFile "/var/run/collectd.pid"
PluginDir "/usr/lib/collectd"
TypesDB "/usr/share/collectd/types.db"
Interval 30
ReadThreads 2

LoadPlugin cpu
<Plugin cpu>
        ValuesPercentage true
        ReportByCpu true
        ReportByState true
</Plugin>

LoadPlugin interface
<Plugin interface>
        IgnoreSelected false
        Interface "br-lan"
</Plugin>

LoadPlugin iwinfo

LoadPlugin load

LoadPlugin memory
<Plugin memory>
        ValuesPercentage false
        ValuesAbsolute true
</Plugin>

LoadPlugin rrdtool
<Plugin rrdtool>
        DataDir "/tmp/rrd"
        RRARows 288
        RRASingle true
</Plugin>

LoadPlugin thermal
```

I did  a forum post: https://forum.openwrt.org/t/cannot-make-luci-app-statistics-collectd-run-well/180445

**Comment by mstojek** [comment]
Remove this part from `/etc/collectd.conf`:
`LoadPlugin thermal`

restart collectd:
`# /etc/init.d/collectd restart`

**Comment by darrepac** [comment]
It worked!!

**Comment by mstojek** [comment]
Does it mean that you see Nlbwmon statistics in Collectd and we can close this issue?

**Comment by darrepac** [comment]
I see generic statistics but not Nlbwmon… i don’t have « firewall » in graph. What can I check?

**Comment by darrepac** [comment]
```
Mon Dec 11 11:46:12 2023 daemon.err collectd[16354]: plugin_load: plugin "lua" successfully loaded.
Mon Dec 11 11:46:12 2023 daemon.err collectd[16354]: Lua plugin: Executing script "/usr/share/collectd-mod-lua/nlbw2collectd.lua" failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:1: module 'luci.jsonc' not found:
```

**Comment by mstojek** [comment]
Hm, I thought that this package comes with standard Luci installation, seems that is not the case.
You need to install one more thing:
`# opkg install luci-lib-jsonc`

**Comment by darrepac** [comment]
```
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]: Lua plugin: Executing script "/usr/share/collectd-mod-lua/nlbw2collectd.lua" failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:2: module 'luci.sys' not found:
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no field package.preload['luci.sys']
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/share/collectd-mod-lua/luci/sys.lua'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file './luci/sys.lua'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/share/lua/luci/sys.lua'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/share/lua/luci/sys/init.lua'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/lib/lua/luci/sys.lua'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/lib/lua/luci/sys/init.lua'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file './luci/sys.so'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/lib/lua/luci/sys.so'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/lib/lua/loadall.so'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file './luci.so'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/lib/lua/luci.so'
Mon Dec 11 12:16:10 2023 daemon.err collectd[22923]:    no file '/usr/lib/lua/loadall.so'
```

**Comment by mstojek** [comment]
Well, strange things happens. I do not want to break your system so next step is at your risk but you may want to first check if you have luci-base installed (which you should since you are using luci):
`# opkg list-installed | grep luci-base`

However if this package is not installed at your risk you can install this:
`# opkg install luci-base`

I wonder if this is standard thing that those libraries do not come with Luci. Do you have by any chance some strange openwrt installation or hardware?

**Comment by darrepac** [comment]
I an using an official firmware (stable)

```
root@OpenWrt:~# opkg list-installed | grep luci-base
luci-base - git-23.306.39416-c86c256

```

**Comment by mstojek** [comment]
I changed the nlbw2collectd.lua script, it uses now luci.util library instead of luci.sys. Give try to the latest script version.

**Comment by darrepac** [comment]
logread output:

```
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: plugin_load: plugin "lua" successfully loaded.
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: Lua plugin: Executing script "/usr/share/collectd-mod-lua/nlbw2collectd.lua" failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:3: module 'luci.util' not found:
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no field package.preload['luci.util']
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/share/collectd-mod-lua/luci/util.lua'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file './luci/util.lua'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/share/lua/luci/util.lua'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/share/lua/luci/util/init.lua'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/lib/lua/luci/util.lua'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/lib/lua/luci/util/init.lua'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file './luci/util.so'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/lib/lua/luci/util.so'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/lib/lua/loadall.so'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file './luci.so'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/lib/lua/luci.so'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]:    no file '/usr/lib/lua/loadall.so'
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: plugin_load: plugin "cpu" successfully loaded.
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: plugin_load: plugin "interface" successfully loaded.
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: plugin_load: plugin "iwinfo" successfully loaded.
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: plugin_load: plugin "load" successfully loaded.
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: plugin_load: plugin "memory" successfully loaded.
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: plugin_load: plugin "rrdtool" successfully loaded.
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: rrdtool plugin: RRASingle = true: creating only AVERAGE RRAs
Mon Dec 11 14:41:17 2023 daemon.err collectd[25589]: Error: Parsing the config file failed!

```

**Comment by mstojek** [comment]
Ok, not good. I removed dependency to luci.util. Try the latest version from github.

**Comment by darrepac** [comment]
```
root@OpenWrt:~# logread | grep collectd
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "lua" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: Lua plugin: File "/usr/share/collectd-mod-lua/nlbw2collectd.lua" loaded successfully
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "cpu" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "interface" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "iwinfo" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "load" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "memory" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "rrdtool" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: rrdtool plugin: RRASingle = true: creating only AVERAGE RRAs
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: Initialization complete, entering read-loop.
Mon Dec 11 15:18:23 2023 daemon.err collectd[5852]: sh: /usr/sbin/nlbw: not found
Mon Dec 11 15:18:23 2023 daemon.err collectd[5852]: Lua plugin: Calling a read callback failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:65: attempt to index local 'pjson' (a nil value)
Mon Dec 11 15:18:23 2023 daemon.err collectd[5852]: read-function of plugin `lua//usr/share/collectd-mod-lua/nlbw2collectd.lua/callback_0' failed. Will suspend it for 60.000 seconds.
```

**Comment by mstojek** [comment]
Do you have nlbwmon installed?

**Comment by darrepac** [comment]
> Do you have nlbwmon installed?

argh forgot to reinstall after firmware upgrade...
Still some errors:
```
root@OpenWrt:~# logread | grep collectd
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "lua" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: Lua plugin: File "/usr/share/collectd-mod-lua/nlbw2collectd.lua" loaded successfully
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "cpu" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "interface" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "iwinfo" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "load" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "memory" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: plugin_load: plugin "rrdtool" successfully loaded.
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: rrdtool plugin: RRASingle = true: creating only AVERAGE RRAs
Mon Dec 11 15:18:22 2023 daemon.err collectd[5852]: Initialization complete, entering read-loop.
Mon Dec 11 15:18:23 2023 daemon.err collectd[5852]: sh: /usr/sbin/nlbw: not found
Mon Dec 11 15:18:23 2023 daemon.err collectd[5852]: Lua plugin: Calling a read callback failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:65: attempt to index local 'pjson' (a nil value)
Mon Dec 11 15:18:23 2023 daemon.err collectd[5852]: read-function of plugin `lua//usr/share/collectd-mod-lua/nlbw2collectd.lua/callback_0' failed. Will suspend it for 60.000 seconds.
Mon Dec 11 15:19:23 2023 daemon.err collectd[5852]: sh: /usr/sbin/nlbw: not found
Mon Dec 11 15:19:23 2023 daemon.err collectd[5852]: Lua plugin: Calling a read callback failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:65: attempt to index local 'pjson' (a nil value)
Mon Dec 11 15:19:23 2023 daemon.err collectd[5852]: read-function of plugin `lua//usr/share/collectd-mod-lua/nlbw2collectd.lua/callback_0' failed. Will suspend it for 120.000 seconds.
Mon Dec 11 15:21:23 2023 daemon.err collectd[5852]: sh: /usr/sbin/nlbw: not found
Mon Dec 11 15:21:23 2023 daemon.err collectd[5852]: Lua plugin: Calling a read callback failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:65: attempt to index local 'pjson' (a nil value)
Mon Dec 11 15:21:23 2023 daemon.err collectd[5852]: read-function of plugin `lua//usr/share/collectd-mod-lua/nlbw2collectd.lua/callback_0' failed. Will suspend it for 240.000 seconds.
Mon Dec 11 15:25:23 2023 daemon.err collectd[5852]: sh: /usr/sbin/nlbw: not found
Mon Dec 11 15:25:23 2023 daemon.err collectd[5852]: Lua plugin: Calling a read callback failed: /usr/share/collectd-mod-lua/nlbw2collectd.lua:65: attempt to index local 'pjson' (a nil value)
Mon Dec 11 15:25:23 2023 daemon.err collectd[5852]: read-function of plugin `lua//usr/share/collectd-mod-lua/nlbw2collectd.lua/callback_0' failed. Will suspend it for 480.000 seconds.
Mon Dec 11 15:26:19 2023 daemon.err collectd[5852]: Exiting normally.
Mon Dec 11 15:26:19 2023 daemon.err collectd[5852]: collectd: Stopping 2 read threads.
Mon Dec 11 15:26:19 2023 daemon.err collectd[5852]: collectd: Stopping 5 write threads.
Mon Dec 11 15:26:19 2023 daemon.err collectd[5852]: rrdtool plugin: Shutting down the queue thread.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: plugin_load: plugin "lua" successfully loaded.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: Lua plugin: File "/usr/share/collectd-mod-lua/nlbw2collectd.lua" loaded successfully
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: plugin_load: plugin "cpu" successfully loaded.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: plugin_load: plugin "interface" successfully loaded.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: plugin_load: plugin "iwinfo" successfully loaded.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: plugin_load: plugin "load" successfully loaded.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: plugin_load: plugin "memory" successfully loaded.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: plugin_load: plugin "rrdtool" successfully loaded.
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: rrdtool plugin: RRASingle = true: creating only AVERAGE RRAs
Mon Dec 11 15:26:19 2023 daemon.err collectd[6770]: Initialization complete, entering read-loop.
```

But I have now something!
![image](https://github.com/mstojek/nlbw2collectd/assets/7128994/d145cf0c-8ad0-4a2d-ba20-3e684daad786)

**Comment by mstojek** [comment]
Great! Do some testing and check how it works.
If you still see error: 
"sh: /usr/sbin/nlbw: not found" 
in the logs let me know.

**Comment by mstojek** [comment]
Please note that I had to change the Nlbwmon config to prevent nlbwmon from stopping collecting data (not sure if this is necessary for your system).
Details can be found here: https://forum.openwrt.org/t/nlbwmon-stops-gathering-data/125221/5?u=mstojek

**Comment by darrepac** [comment]
ok I will let it run a bit and see. My goal being to then export to influxdb/grafana like I did in the past with iptmon
