### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by moookino** [mstojek/nlbw2collectd#2]
Hi @mstojek 

Can you share how to setup Grafana/influxdb to show nice reports you've?
I was trying to review influxdb data, but I can't find firewall part exported here

**Comment by darrepac** [comment]
On my side, I have taken the settings from iptmon script but I have the same issue: no data seems to arrive in the influxdb database. What can we check?
I have enable the "Network" output plugin in Collectd settings (with my server ip and 25826 port) and change the 2 lines in the lua script to mimic iptmon behaviour

**Comment by mstojek** [comment]
When configuring Grafana/Influx I was basing on nice instructions from Pommi:
Influxdb v1 (InfluxQL based): https://cloud-infra.engineer/collectd-influxdb-grafana-with-downsampling/
Influxdb v2 (Flux based): https://cloud-infra.engineer/collectd-influxdb2-grafana-with-downsampling/
Note that in InfluxDB v3 they plan to drop support for Flux.....
Those instruction allow you to get also downsampling but you can skip this part.

For the dashboard you can use either Pommi: https://grafana.com/grafana/dashboards/10179-collectd-graph-panel/ or 
Oofnikj solution: https://grafana.com/grafana/dashboards/11858-openwrt/ or any other you find that suits your needs.

**Comment by moookino** [comment]
@darrepac 
I was able to get the data, I had configuration issues, followed this guide https://centurio.net/2023/10/10/show-collectd-data-from-openwrt-in-grafana/ which should provide more insight how it should look E2E
