### ISSUE TITLE
Time Stamped total usage..

### ISSUE THREAD

**Issue by fawzy46** [mstojek/nlbw2collectd#6]
Hi, I have a small question about the script. can the total usage data be filtered with time range?

**Comment by mstojek** [comment]
You can filter this using collectd data browsers like CGP: https://github.com/pommi/CGP. In default config you can watch usage divide by howr.day,week etc.
You can also export the usage to influxdb/grafana and then you will have huge flexibility in watching the data usage (grafana provides very flexible filters)
